#!/usr/bin/env bash
set -e

REAL=0

while getopts r opt;
do
    case $opt
        in
        r)REAL=1;;
    esac
done

if [ $REAL -eq 1 ]; then
    echo "Registering slash commands in production"
    export SETTINGS_MODULE=common.settings.production.SlashCommandRegisterProductionSettings
else
    echo "Registering slash commands in localdev"
    export SETTINGS_MODULE=common.settings.localdev.SlashCommandRegisterLocalDevSettings
fi
python register_slash_commands.py
