#!/usr/bin/env bash
# Create a deployment package for AWS Lambda
mkdir -p package

# Install dependencies
pip install -r requirements.txt --target ./package

# Add the Lambda function code to the deployment package
zip -r deployment-package.zip package/ squash_bot/ lambda_function.py -x "*/__pycache__/*"