#!/usr/bin/env bash
# Delete the existing deployment package
rm deployment-package.zip

# Delete the package directory
rm -r package

# Create a deployment package for AWS Lambda
mkdir -p package

# Install dependencies
pip install -r requirements.txt --target ./package

# Add the Lambda function code to the deployment package
zip -r deployment-package.zip package/ squash_bot/ lambda_function.py -x "*/__pycache__/*"